### ISSUE TITLE
And the mysterious author is here :)

### ISSUE THREAD

**Issue by mbonaci** [birdwing/Brackets-MBO-Theme#2]
Would you mind giving me some credit in readme & Brackets description?
https://github.com/mbonaci/global/blob/master/Mbo.tmTheme

**Comment by birdwing** [comment]
I apologize for not having this.
I originally found the theme here https://github.com/Jacse/themes-for-brackets
Jacse didn't mention you were the author of the theme in his code.

I made the theme because Brackets included native support for themes and I wanted to get rid of the themes-for-brackets extension because of this and couldn't find this theme anywhere.

**Comment by mbonaci** [comment]
No need for apologies, you did a good thing.
Between my work and 9m old twins, I wouldn't get to this any time soon :)
Oh, and BTW, I first contributed the theme to Jacse Brackets plugin, but afterwards it made into official CodeMirror themes.
Since I'm not much of a CSS expert, you could possibly do me a favor and send a pull request with mod that fixes matching bracket highlight (only happens in Brackets) here:
[https://github.com/marijnh/CodeMirror/blob/master/theme/mbo.css](https://github.com/marijnh/CodeMirror/blob/master/theme/mbo.css)
If you do that, please keep in mind that the theme must not contain anything specific to Brackets.
Thanks :+1:
